### ISSUE TITLE
No API to query for current camera parameters

### ISSUE THREAD

**Issue by ezaquarii** [Fotoapparat/Fotoapparat#107]
#### What are you trying to achieve or the steps to reproduce?

I want to display picture size selection menu with currently used picture size,
but the Fotoapparat API doesn't expose current camera parameters.

Those parameters are kept in `ParametersProvider` instance, that is not accessible.

#### What did you expect?

I expect information about current camera settings to be available after `start()`.

**Comment by Diolor** [comment]
You can get the capabilities a camera has with [`Fotoapparat#getCapabilities()`](https://github.com/Fotoapparat/Fotoapparat/blob/master/fotoapparat/src/main/java/io/fotoapparat/Fotoapparat.java#L191). Are you looking for something more than those capabilities?

**Comment by ezaquarii** [comment]
I'm not interested in capabilities, but currently selected resolution.

When camera is started with default settings, I can't tell which defaults are currently active.
I can't use capabilities to initialize the camera, because it becomes available... after you start the camera.

**Comment by friendoye** [comment]
@Diolor @dmitry-zaitsev Probaly closed with #108.
