### ISSUE TITLE
is there any feature to show live camera preview?

### ISSUE THREAD

**Issue by developer--** [Fotoapparat/Fotoapparat#113]
I want to add some filters in preview, like gamma and etc

**Comment by andrewcking** [comment]
You should be able to do this with the .frameProcessor(myFrameProcessor) argument when creating your fotoapparat instance, or are you looking to do something else?

**Comment by developer--** [comment]
do you have any example of how to process this frame? I couldn't create bitmap from this frame, tried to get bytes from frame and than converting it to bitmap, but it returns null

**Comment by fbarrosodev** [comment]
The bitmap is null because the image is in NV21 format.
Check this to convert the byte[] to bitmap.
https://stackoverflow.com/a/32793908/4148930

**Comment by sksar** [comment]
This library can help,
[https://github.com/silvaren/easyrs](https://github.com/silvaren/easyrs)

**Comment by Diolor** [comment]
Editing a photo/video/surface/preview stream is another topic and nothing this library can do :) Hope you found your solution!
