### ISSUE TITLE
How to Create file from photo result?

### ISSUE THREAD

**Issue by jinesh08** [Fotoapparat/Fotoapparat#116]
Please check if your issue exists.

Issues should only be posted after you have been able to reproduce them and confirm that they are either a missing functionality or a bug. 

#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality.

```java
// Wrap code in markdown source tags
```

#### How did you initialize FA?

```java
// Wrap code in markdown source tags
```

#### Context:

* *FA version*:
* *Devices/APIs affected*:
* *any other relevant information*:

**Comment by Diolor** [comment]
Please see the sample https://github.com/Fotoapparat/Fotoapparat/blob/master/sample/src/main/java/io/fotoapparat/sample/MainActivity.java#L212
