### ISSUE TITLE
Aspect ratio of the preview is broken sometimes while using Camera2

### ISSUE THREAD

**Issue by dmitry-zaitsev** [Fotoapparat/Fotoapparat#13]
Device: S7 Edge

This screen is actually 30" and certainly not square :)

![230114212_14125708121819806030 1](https://cloud.githubusercontent.com/assets/2990722/25607853/bdf38bd8-2f18-11e7-98f2-c974ccff6325.jpg)

**Comment by Diolor** [comment]
I expect this to be duplicate of #5. Will leave open for now.

**Comment by dmitry-zaitsev** [comment]
It is not duplicate, because in #5 aspect ratio is actually correct (as you can see from rectangle).

**Comment by Diolor** [comment]
Not after the click.
Looks the same issue because on start preview there is a change of this stretching but always after a take photo (which call start preview again) as in #5.

**Comment by Diolor** [comment]
Should be fixed. @dmitry-zaitsev please confirm by closing the ticket:)

**Comment by dmitry-zaitsev** [comment]
@Diolor no, issue is still here :(

**Comment by dmitry-zaitsev** [comment]
As discussed, let's move it to 1.1.0, since we are going to disable Camera2 for now.

**Comment by Diolor** [comment]
I will close this v2 issue for now.
