### ISSUE TITLE
cancelBuffer: BufferQueue has been abandoned 

### ISSUE THREAD

**Issue by buelersandra** [Fotoapparat/Fotoapparat#132]
cancelBuffer: BufferQueue has been abandoned is logged after camera is started and stopped and view is dismissed without taking a picture.
When the view is called again the cameraview is not displayed.

**Comment by Diolor** [comment]
You cannot take a picture after you have stopped the camera.

Could you explain further `When the view is called again the cameraview is not displayed.`? FA initialization etc...

**Comment by Diolor** [comment]
I will close this due to insufficient info
