### ISSUE TITLE
Disable confirmation after take photo

### ISSUE THREAD

**Issue by core2root** [Fotoapparat/Fotoapparat#144]
hi , is there are way to disable "use photo" & "retake" option and immediately return the result?

**Comment by dmitry-zaitsev** [comment]
Sorry, but it is not clear what your question is. Could you please provide more details?

I will close the issue until new details are available.

**Comment by core2root** [comment]
hi, i have other issue i cant start the preview, it shows nothing.
i set the builder as in your tutorial 

fotoapparat = Fotoapparat.with(this)
                .into(cameraView)
                .previewScaleType(ScaleType.CENTER_CROP)
                .lensPosition(LensPositionSelectors.back())
                .previewSize(SizeSelectors.biggestSize())
                .photoSize(SizeSelectors.biggestSize())
                .build();
@Override
    protected void onStart() {
        super.onStart();

        fotoapparat.start();
    }

**Comment by dmitry-zaitsev** [comment]
Make sure that you have the camera permission
