### ISSUE TITLE
Add antibanding parameter

### ISSUE THREAD

**Issue by simone-gasparini** [Fotoapparat/Fotoapparat#154]
There is a way to manually define antibanding parameter?
In some cases the taken photo will present black lines due to "improper" illumination.

Camera parameter documented here:
[https://developer.android.com/reference/android/hardware/Camera.Parameters.html#getAntibanding()](https://developer.android.com/reference/android/hardware/Camera.Parameters.html#getAntibanding())

**Comment by Diolor** [comment]
Hey! I also see a [setter](https://developer.android.com/reference/android/hardware/Camera.Parameters.html#setAntibanding(java.lang.String)), so yes you can do it. If you implement it, feel free to make a PR!

**Comment by simone-gasparini** [comment]
Closed with #158
