### ISSUE TITLE
Read out biggestSize() width and height

### ISSUE THREAD

**Issue by koenschauwaert** [Fotoapparat/Fotoapparat#155]
I want to read out the actual sizes (width and height) of 
```java
Fotoapparat.photoSize(standardRatio(biggestSize()))
```

How do I accomplish this?

**Comment by Diolor** [comment]
You can read the bitmap dimensions from the bytearray

**Comment by dmitry-zaitsev** [comment]
Alternatively, you can apply selector function (that's what `biggestSize()` is) to the `Capabilities`. Like that:

```
val result = biggestSize().select(capabilities.supportedPictureSizes())
```

To get capabilities check `fotoapparat.getCapabilities`.
