### ISSUE TITLE
Error "Failed to open camera with lens position: [NAME] and id: [ID]"

### ISSUE THREAD

**Issue by koenschauwaert** [Fotoapparat/Fotoapparat#156]
When I just start the app, nothing goes wrong. I can switch between front and rear (I used the Sample code), I can make a picture, go to a new activity and view this picture, but when pressing the back button... 
```java
@Override
public void onBackPressed(){
    super.onBackPressed();
}
```
...to return to the activity where my cameraview is shown, I get the following error:

```java
io.fotoapparat.b.b: Failed to open camera with lens position: BACK and id: 0
```
And
```java
io.fotoapparat.b.b: Failed to open camera with lens position: FRONT and id: 1
```

# Context
Devices:
- Moto X 2013 // API 22 // LineageOS
- Xiaomi Mi5S // API 25 // LineageOS
- Huawei P10 // API 25 // Original EMUI ROM

I use the newest library:
```java
implementation 'io.fotoapparat.fotoapparat:library:1.5.0'
```

**Comment by Diolor** [comment]
Can you please paste or upload the code which is not working?

**Comment by devangichhatbar** [comment]
The same issue facing. 
![whatsapp image 2018-10-21 at 11 59 10 am](https://user-images.githubusercontent.com/13677061/47263930-f0ca5480-d528-11e8-8494-826f0d0016a5.jpeg)

When I click on the bottom tab and then click on camera there is the blank screen.
