### ISSUE TITLE
How to get URI of photo?

### ISSUE THREAD

**Issue by ArtworkAD** [Fotoapparat/Fotoapparat#16]
After

    photoResult.saveToFile(someFile)

how can I retrieve the URI of the saved image?

**Comment by Diolor** [comment]
The File java class has your answer:

```java
File file = new File(
        getExternalFilesDir("photos"),
        "photo.jpg"
);
photoResult.saveToFile(file);
file.toURI(); <-- here you go
```

Also see: https://github.com/Fotoapparat/Fotoapparat/blob/master/sample/src/main/java/io/fotoapparat/sample/MainActivity.java#L87
