### ISSUE TITLE
bug!!!!

### ISSUE THREAD

**Issue by MinchinWang** [Fotoapparat/Fotoapparat#161]
java.lang.RuntimeException:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: takePicture failed, error=-38
2 io.fotoapparat.result.PendingResult.getResultUnsafe(PendingResult.java:129)
3 ......
4 Caused by:
5 java.lang.RuntimeException:takePicture failed, error=-38
6 android.hardware.Camera.native_takePicture(Native Method)
7 android.hardware.Camera.takePicture(Camera.java:1772)
8 io.fotoapparat.hardware.v1.Camera1.takePicture(Camera1.java:285)
9 io.fotoapparat.routine.picture.TakePictureTask$1.call(TakePictureTask.java:26)
10 io.fotoapparat.routine.picture.TakePictureTask$1.call(TakePictureTask.java:21)
11 java.util.concurrent.FutureTask.run(FutureTask.java:237)
12 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
13 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
14 java.lang.Thread.run(Thread.java:776)

**Comment by Diolor** [comment]
This is a native camera exception and we cannot do much. You may try v2.0.0-beta2 where we suppress those exceptions
