### ISSUE TITLE
App is crashing while rotate screen continuously on Samsung galaxy on 5

### ISSUE THREAD

**Issue by GrishmaPromact** [Fotoapparat/Fotoapparat#164]
Today, I just take latest from fotoappart and app is still crashing while rotating screen continuously.
PFA, Crash log screenshot.
![image](https://user-images.githubusercontent.com/20226076/34467401-95a40c5c-ef16-11e7-8025-c82488ce49a2.png)

Please do needful.

**Comment by Diolor** [comment]
I cannot reproduce neither on Nexus 6 nor on a Pixel 2

**Comment by GrishmaPromact** [comment]
But it is crashing in Samsung devices. Please check it in Samsung mobile.

**Comment by GrishmaPromact** [comment]
@Diolor Same crash accrued in moto M device.

**Comment by GrishmaPromact** [comment]
@Diolor It is not resolved.. Why are you close my issue?

**Comment by GrishmaPromact** [comment]
@Diolor Thanks. This crashed is resolved. Another crash came while doing same. 
PFA, of crashed log.

![image](https://user-images.githubusercontent.com/20226076/34509206-5e71c4ba-f06d-11e7-9f89-9a24b34d281a.png)
