### ISSUE TITLE
Photo is not rotated correctly in Camera1

### ISSUE THREAD

**Issue by Diolor** [Fotoapparat/Fotoapparat#17]
Device: Nexus 6P

Potentially due to sensor orientation degrees as camera 2 with other devices (  #12 ).

![device-2017-05-09-231456](https://cloud.githubusercontent.com/assets/1686807/25873108/6d299c7e-350d-11e7-994a-ecd96eaa88b3.png)

**Comment by dmitry-zaitsev** [comment]
@Diolor could you please tell me which parameters do you receive in `OrientationUtils#computeImageOrientation` and what is the output of the method?

**Comment by Diolor** [comment]
For Pixel XL:
Front camera:
`screenRotationDegrees : 0, cameraRotationDegrees: 270, cameraIsMirrored: true`
Output is at 90.
Back camera:
`screenRotationDegrees : 0, cameraRotationDegrees: 90, cameraIsMirrored: false`
Output is at 270.

For Nexus 6P:
Back/Front camera:
`screenRotationDegrees : 0, cameraRotationDegrees: 90, cameraIsMirrored: false/true`
Output is both at 270.

**Comment by dmitry-zaitsev** [comment]
All good, I can reproduce it on my Nexus 5X.

**Comment by dmitry-zaitsev** [comment]
@Diolor could you please check if `fix/issue-17` branch works for you with Camera1 and Camera2?

**Comment by Diolor** [comment]
both look ok on my 6P

**Comment by dmitry-zaitsev** [comment]
Fixed now.
