### ISSUE TITLE
Taking photo using Camera2 is slower than Camera1

### ISSUE THREAD

**Issue by dmitry-zaitsev** [Fotoapparat/Fotoapparat#18]
Not sure why, but taking pictures with Camera2 is couple of seconds slower then Camera1. I suspect that it might be related to re-focusing the camera.

**Comment by Diolor** [comment]
Both `autoFocus` and `measureExposure` are adding time in the `TakePictureTask`.
We could cut the autofocus but I am gathering more info about the full behavior of exposure metering and flash.

**Comment by Diolor** [comment]
I will close this v2 related issue for now
