### ISSUE TITLE
Updata Camera Configuration in JAVA not working

### ISSUE THREAD

**Issue by monowar1993** [Fotoapparat/Fotoapparat#183]
#### What am I trying to achieve or the steps to reproduce?
I have been trying to update camera configuration. But it was not updating when I used JAVA codes. But working fine with kotlin. Tested on you Sample app also. 

#### How did I initialize FA?
```
Cameraconfiguration = CameraConfiguration.builder()
                .focusMode(firstAvailable(continuousFocusPicture(), autoFocus(), fixed()))
                //.flash(firstAvailable(autoFlash(), torch(), off(), on()))
                .flash(off())
                .previewResolution(highestResolution())
                .previewFpsRange(highestFps())
                .photoResolution(highestResolution())
                .jpegQuality(highestQuality())
                .antiBandingMode(auto())
                .sensorSensitivity(highestSensorSensitivity())
                .build();

Fotoapparat fotoapparat = new Fotoapparat(getActivity(), binding.cameraView, binding.focusView, back(),
ScaleType.CenterCrop, configuration, e -> {
            e.printStackTrace();
            return null;
        }, loggers(logcat(), fileLogger(getActivity())));
```

and update using 
`fotoapparat.updateConfiguration(UpdateConfiguration.builder().flash(on()).build());`
this seems not to be working. As the parameters are not updated. I tried to change the photoResolution() also. But parameters are not updated. They are same as the way I initialized them.
but bellow is working fine
`fotoapparat.updateConfiguration(configuration.builder().flash(on()).build());`

#### What did I expect?
I expected that
`fotoapparat.updateConfiguration(UpdateConfiguration.builder().flash(on()).build());`
this code would work perfectly on JAVA as it is working fine in kotlin. 

#### Context:

* *FA version: 2.1.2*:
* *Device: Nexus 5, 7.1.1, LineageOS Custom ROM*:

Many thanks for making such a good Camera Library

**Comment by Diolor** [comment]
Thanks for reporting this! Will be fixed in the next release
