### ISSUE TITLE
How to switch between camera1 and camera2? How to switch camera from front to back or vice versa?

### ISSUE THREAD

**Issue by shivam2702** [Fotoapparat/Fotoapparat#20]

**Comment by dmitry-zaitsev** [comment]
We do not yet have a defined API for switching between the cameras, but it is in the works and has a high priority (right below all the bugs). For now as a temporary solution I suggest creating 2 instances of `Fotoapparat` - one for front camera and one for back camera.

**Comment by shivam2702** [comment]
ohk Thanks and now why don't you push a stable version?
I think current snapshot version is one of the best and very well stable .

**Comment by Diolor** [comment]
@shivam2702 There are few issues we still want to resolve. Especially the aspect ration in camera2. You can check what's left here: https://github.com/Fotoapparat/Fotoapparat/milestone/1

**Comment by Diolor** [comment]
Fixed on #27

**Comment by dmitry-zaitsev** [comment]
@shivam2702 sample app now allows you to switch between the cameras. You can use it as an example.

**Comment by shivam2702** [comment]
Thank you buddy. 
and Congratulations for the first release...
