### ISSUE TITLE
Configuration  Issue with Java

### ISSUE THREAD

**Issue by DvlopRyanSpears** [Fotoapparat/Fotoapparat#204]
Hi,i'm trying use this library with Java,

>  mFotoapparat = Fotoapparat
                .with(this)
                .into(cameraView_fotoapparat)          
                .previewScaleType(ScaleType.CenterCrop)  
                .photoResolution(new Function1<Iterable<Resolution>, Resolution>() {
                    @Override
                    public Resolution invoke(Iterable<Resolution> resolutions) {
                        return new Resolution(1080,1200);
                    }
                }).lensPosition(new Function1<Iterable<? extends LensPosition>, LensPosition>() {
                    @Override
                    public LensPosition invoke(Iterable<? extends LensPosition> lensPositions) {
                        return null;  
//Here's the issue  that i'm facing. I don't know how to create a LensPosition object. since the //LensPosition class is a 'sealed' class and it's child class are not defined as static class inside of //LensPosition .
                    }
                })
               .build();

**Comment by Diolor** [comment]
e.g. `LensPositionSelectorsKt.front()`for front camera or `back()` for the back one.

Note that you resolution is also hardcoded which might not work for all devices: some devices might not support 1080x1200 resolution.

**Comment by DvlopRyanSpears** [comment]
Thanks for your reply.
For the resolution problem, Shall i query the device's max supported resolution before i settle ?

**Comment by Diolor** [comment]
We already have an example here about highest resolution: https://github.com/Fotoapparat/Fotoapparat/wiki/Configuration-Java

Available selectors are listed here:https://github.com/Fotoapparat/Fotoapparat/tree/master/fotoapparat/src/main/java/io/fotoapparat/selector

**Comment by ARSOFT1** [comment]
LensPositionSelectorsKt.front() is not working.....Update your code

**Comment by ARSOFT1** [comment]
builder =Fotoapparat.with(this).into(binding.cameraView)
                .previewScaleType(ScaleType.CenterCrop)  // we want the preview to fill the view
                .photoResolution(ResolutionSelectorsKt.highestResolution())// we want to have the biggest photo possible
                .lensPosition(LensPositionSelectorsKt.front())
                .focusMode(SelectorsKt.firstAvailable(  // (optional) use the first focus mode which is supported by device
                        FocusModeSelectorsKt.continuousFocusPicture(),
                        FocusModeSelectorsKt.autoFocus(),        // in case if continuous focus is not available on device, auto focus will be used
                        FocusModeSelectorsKt.fixed()             // if even auto focus is not available - fixed focus mode will be used
                ))
                .flash(SelectorsKt.firstAvailable(      // (optional) similar to how it is done for focus mode, this time for flash
                        FlashSelectorsKt.autoRedEye(),
                        FlashSelectorsKt.autoFlash(),
                        FlashSelectorsKt.torch()
                ));
