### ISSUE TITLE
How to enable 'tap to focus' in my Fotoapparat java activity?

### ISSUE THREAD

**Issue by iamutkarshtiwari** [Fotoapparat/Fotoapparat#214]
Please check if your issue exists.

Issues should only be posted after you have been able to reproduce them and confirm that they are either a missing functionality or a bug. 

#### What are you trying to achieve or the steps to reproduce?

I checked the sample app but the MainActivity.kt is in kotlin and I didn't find any code for adding the tap-to-focus in the Activity.java. Could anyone please point me in the right direction?

```java
// Wrap code in markdown source tags
```

#### How did you initialize FA?

```java
// Wrap code in markdown source tags
```

#### Context:

* *FA version*:
* *Devices/APIs affected*:
* *any other relevant information*:

**Comment by Diolor** [comment]
Hey! @Diederikjh already helped us with this and added the example in the ActivityJava. Take a look again in the master branch!

**Comment by iamutkarshtiwari** [comment]
@Diolor I am unable to access the ```.focusView()``` method of Fotoapparat builder.

![screen shot 2018-02-20 at 1 31 22 pm](https://user-images.githubusercontent.com/6258810/36407511-7bb80cb4-1642-11e8-904e-5163e7aa218e.png)

**Comment by Diolor** [comment]
Which version are you using?

**Comment by iamutkarshtiwari** [comment]
@Diolor I am using ```2.2.0```. Thank you for the suggestion :)
