### ISSUE TITLE
Image is being saved in a different orientation from that of the screen

### ISSUE THREAD

**Issue by Nkurayijahubert** [Fotoapparat/Fotoapparat#218]
Hello,

Am facing an issue, where image is being saved in different orientation from that of screen, if screen is in portrait mode image will be in landscape and vise-versa. Any help!

**Comment by Diolor** [comment]
Front or back camera? Also which device?

**Comment by scifinder** [comment]
A similar problem. In landscape mode, the second shot has an incorrect orientation. Steps:
1. Turn the screen horizontally (Samsung Galaxy A3).
2. Take a picture, display it on the preview.
3. Go back. Make a second photo.
4. The second picture will be shot perpendicularly.
![bug](https://user-images.githubusercontent.com/11472748/36946569-59f30422-1ff1-11e8-8d85-7bed8a152ac7.png)

**Comment by Diolor** [comment]
That's a different issue @scifinder, thanks. It's already reported in #193

**Comment by Nkurayijahubert** [comment]
@Diolor it's on back camera, on Nexus 5x phone.

**Comment by ShkurtiA** [comment]
any solutions or workarounds yet?

**Comment by Nkurayijahubert** [comment]
I would like to ask the same, @Diolor

**Comment by Nkurayijahubert** [comment]
@Diolor,  Any solution?

**Comment by Diolor** [comment]
No, but you can send a PR @Nkurayijahubert !

**Comment by dmitry-zaitsev** [comment]
@Nkurayijahubert could you please share a sample photo with us?

**Comment by Nkurayijahubert** [comment]
![device-2018-03-26-151524](https://user-images.githubusercontent.com/8438900/37931933-6b9bbf90-3147-11e8-8e43-bcee7958c84b.png)

@dmitry-zaitsev Here is the sample image

**Comment by Nkurayijahubert** [comment]
@dmitry-zaitsev as you can see phone is in portrait orientation but the image comes in landscape orientation

**Comment by dmitry-zaitsev** [comment]
@Nkurayijahubert please share the actual JPG image, not just the screenshot. I am trying to figure out what Exif properties the file has.

**Comment by Nkurayijahubert** [comment]
Ok, here it's @dmitry-zaitsev 

![tagshop_ishimwe_i2018_03_26_15_15_03](https://user-images.githubusercontent.com/8438900/37955112-f6b4f9b0-31a7-11e8-9c33-2bd8124044d5.jpg)

**Comment by Nkurayijahubert** [comment]
@dmitry-zaitsev  before to open it's in landscape but in preview it become portrait, as you can see in that comment above.

**Comment by dmitry-zaitsev** [comment]
@Nkurayijahubert this is not the bug of Fotoapparat but the missing feature in your image viewer. The JPG file contains information about the image orientation and it is a responsibility of the viewer to rotate the image accordingly.

**Comment by Nkurayijahubert** [comment]
@dmitry-zaitsev what do you mean by image viewer? is it manufacturing issue or how the user has configured?

**Comment by dmitry-zaitsev** [comment]
@Nkurayijahubert by the viewer I mean the Android application you use to view the image on your device.

**Comment by Nkurayijahubert** [comment]
Ok, Thank you @dmitry-zaitsev let try to fix the issue

**Comment by antoineFrau** [comment]
Hi so I was facing this issue, and figure out that I just needed to rotate the image of 90 degrees if the width < height, meaning that the image is in landscape mode.

```kotlin
photoResult?.toBitmap()?.whenAvailable { photo ->
    photo?.apply {
        // Avoid the landscape image preview
       var bitmap = if (this.bitmap.width < this.bitmap.height) this.bitmap else this.bitmap.rotate(90)
        Log.i(LOGGING_TAG, "New photo captured. Bitmap length: ${this.bitmap.byteCount}")
    }
        ?: Log.e(LOGGING_TAG, "Couldn't capture photo.")
}
```
