### ISSUE TITLE
How to Compile this Library?

### ISSUE THREAD

**Issue by chnouman** [Fotoapparat/Fotoapparat#22]
i didnt find x.y.x values for     compile 'io.fotoapparat.fotoapparat:library:x.y.z'
please help.

**Comment by dmitry-zaitsev** [comment]
Use `-SNAPSHOT` as a version. Like that:

```groovy
compile 'io.fotoapparat.fotoapparat:library:-SNAPSHOT'
```

**Comment by chnouman** [comment]
ok thanks dear
