### ISSUE TITLE
performClick was lost =)

### ISSUE THREAD

**Issue by scifinder** [Fotoapparat/Fotoapparat#220]
Hello! =)
I decided to implement the zoom with gestures. On my construction `cameraView.setOnTouchListener(new View.OnTouchListener() { ...` I receive a warning: 

> Custom view "CameraView" has setOnTouchListener called on it but does not override performClick.

I tried to extend the class CameraView so to add `@Override performClick(...)`, but I get error like "**final** class can not be overridden". Can you add it on you source? =)

**Comment by Diolor** [comment]
We would be happy to accept a PR!

**Comment by scifinder** [comment]
I'm not sure, but I think something needs to be done in CameraView class:
```
@Override
public boolean performClick() {
        super.performClick();
        return true;
}
```

**Comment by dmitry-zaitsev** [comment]
@scifinder you can safely ignore this warning - it does not really point at any real issues in the implementation. Thanks for reporting though 👍
