### ISSUE TITLE
Bug: Illegal lens position on very specific device

### ISSUE THREAD

**Issue by siga111** [Fotoapparat/Fotoapparat#224]
I personally was not able to reproduce this is issue and I have a serious suspicion that it is very device specific. Still I think it is something that should be reported.

#### What are you trying to achieve or the steps to reproduce?

Following crash report came in Fabric:
```
Caused by java.lang.IllegalArgumentException: Lens position 2 is not supported.
       at io.fotoapparat.characteristic.LensPositionCharacteristicKt.toLensPosition(LensPositionCharacteristic.kt:19)
       at io.fotoapparat.characteristic.CameraInfoProviderKt.getCharacteristics(CameraInfoProvider.kt:13)
       at io.fotoapparat.hardware.Device.<init>(Device.kt:38)
       at io.fotoapparat.hardware.Device.<init>(Device.kt:31)
       at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:61)
       at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:54)
```
From what I understand [this function is the source of exception](https://github.com/Fotoapparat/Fotoapparat/blob/master/fotoapparat/src/main/java/io/fotoapparat/characteristic/LensPositionCharacteristic.kt#L15:L20). Somehow [Camera.CameraInfo](https://developer.android.com/reference/android/hardware/Camera.CameraInfo.html) constants have value other than specified in docs. 

The only device with this crash is [Leagoo T5](http://www.leagoo.com/product/t5/).

What would be the proper way of handling such cases?

#### Context:

* *FA version*: 2.2.0
* *Devices/APIs affected*: Leagoo T5, Android 7.0

**Comment by Diolor** [comment]
I hope that `position 2` means external (at least in [camera 2](https://developer.android.com/reference/android/hardware/camera2/CameraMetadata.html#LENS_FACING_EXTERNAL)). So we can simply add a case when position is 2 to return `LensPosition.External`.

Feel free to send a PR!
