### ISSUE TITLE
[Question] Translate to java

### ISSUE THREAD

**Issue by scifinder** [Fotoapparat/Fotoapparat#225]
Hi! I can not translate this line into Java.
https://github.com/Fotoapparat/Fotoapparat/blob/5abcbf7e54dc98f618a5b6cd951dcc8f0ff45206/sample/src/main/java/io/fotoapparat/sample/MainActivity.kt#L158
`capabilities.getFlashModes().contains(new Flash.On())` generate error "On() has private access"

**Comment by Diolor** [comment]
`Flash.On.INSTANCE`?

**Comment by scifinder** [comment]
Yes, it works! =) Thank you! =)
