### ISSUE TITLE
Taken pic wrong orientation

### ISSUE THREAD

**Issue by tapeo** [Fotoapparat/Fotoapparat#233]
When auto rotation is not locked, when device is in landscape, the pic taken showed rotated even with `-bitmapPhoto.rotationDegrees`. If i lock rotation the result is ok. It has wrong result in Oneplus 3T too in landscape, but with front camera. Any solutions? If you need any other information ask me for them thank you!

FA version: 2.2.0
Devices/APIs affected: Google Pixel / Oneplus 3T

**Comment by Diolor** [comment]
Dup of #193
