### ISSUE TITLE
whenAvailable callback for saveToFile(FIle file)

### ISSUE THREAD

**Issue by sinnott-balin** [Fotoapparat/Fotoapparat#24]
Hey guys, is it possible to trigger a callback when saveToFile has finished execution?  I've been trying to create a new PendingResult.Callback but can't seem to figure out the proper Callback type.
 
       PhotoResult photoResult = fotoapparat.takePicture();

        File f = new File(
                getActivity().getExternalFilesDir("photos"),
                "newImage.jpg"
        );

        PendingResult.Callback<?> callback = new PendingResult.Callback<Void>() {
            @Override
            public void onResult(Void v) {
                Log.d(TAG,"SAVE FILE CALLBACK");
            }
        };

        photoResult.saveToFile(f).whenAvailable(callback);

**Comment by dmitry-zaitsev** [comment]
This is something I overlooked while writing `saveToFile()`. Fixed.

Now `saveToFile` expects `Callback<Void>` instead of `Callback<?>`. Moreover, I added new method - `.whenDone` which is exactly the same as `whenAvailable` but has a name better suited for `Void` callbacks.
