### ISSUE TITLE
 Why is bitmap null?  

### ISSUE THREAD

**Issue by mqwangios** [Fotoapparat/Fotoapparat#243]
Why is bitmap null?  

private class SampleFrameProcessor implements FrameProcessor {
        @Override
        public void process(@NotNull Frame frame) {
            // Perform frame processing, if needed
            Bitmap bitmap = BitmapFactory.decodeByteArray(frame.getImage(), 0, frame.getImage().length);
            ImageView imageView = findViewById(R.id.result);
            imageView.setImageBitmap(bitmap);
        }

**Comment by dmitry-zaitsev** [comment]
Frames of the `FrameProcessor` are in NV21 format which can't be decoded using `BitmapFactory`. You can still convert it to `Bitmap` but you would have to use another approach: https://stackoverflow.com/questions/32276522/convert-nv21-byte-array-into-bitmap-readable-format

**Comment by mqwangios** [comment]
How to set the output size, I think the output is 1080*1920?
![a05ea813-0a43-48c5-b20d-f4a2e49b726c](https://user-images.githubusercontent.com/35474578/40274783-46a59e90-5c12-11e8-82f6-9e7ff98886de.png)

**Comment by bagage** [comment]
For anyone interested, most straightforward method is to use [easyrs](https://github.com/silvaren/easyrs) library:

```gradle
//in build.gradle
implementations 'io.github.silvaren:easyrs:0.5.3'
```

Then convert NV21 to bitmap: 

```java
RenderScript rs = RenderScript.create(context); // where context can be your activity, application, etc.
Bitmap outputBitmap = Nv21Image.nv21ToBitmap(rs, nv21ByteArray, width, height); // where nv21ByteArray contains the NV21 image data
```
