### ISSUE TITLE
How do you tell if the Fotoappart is Started

### ISSUE THREAD

**Issue by markGilchristBookingBug** [Fotoapparat/Fotoapparat#29]
could you add a getter for 

private boolean started;
 

so the when I call 

@Override
    public void onPause() {
        super.onPause();
        fotoapparat.stop();
      ....
    }

I can do 

@Override
    public void onPause() {
        super.onPause();
       if(fotoappart.isStarted()) fotoapparat.stop();
    }

**Comment by Diolor** [comment]
Hey. Why don't you add the `private boolean started;` in the class where you are calling FA's start/stop and set it `true` after you start FA?

We think this method is not needed for everyone to be part of the library, so we would prefer to not expand the API if it can be avoided.
