### ISSUE TITLE
onResult not called in android N

### ISSUE THREAD

**Issue by shayanpourvatan** [Fotoapparat/Fotoapparat#36]
First of all thanks for your great library, I've ran sample code into android emulator API version 25, but `onResult` not called in `photoResult` for saved image, I've test your code in Sony API 23 and it's work fine.

Can you help me to fix this issue.

**Comment by Diolor** [comment]
Thanks @shayanpourvatan for reporting. Might be affecting only emulator. N devices are ok for me but we need to check first. Might be related to file URIs/paths

**Comment by Diolor** [comment]
Ok. Issue is that autofocus is not happening/completing in emulator

**Comment by shayanpourvatan** [comment]
Thanks @Diolor

**Comment by dmitry-zaitsev** [comment]
Implementation on emulator violates JavaDoc of the Camera, so, unfortunately, we are not able to help here without introducing hacks. If this issue will appear on a real device we will take a look again.
