### ISSUE TITLE
IllegalStateException - a.k - Critical exception reported by Firebug 

### ISSUE THREAD

**Issue by jeffersonlicet** [Fotoapparat/Fotoapparat#37]
```
 Exception java.lang.IllegalStateException: Preview stream is null. Make sure camera is opened.
io.fotoapparat.a.d.a.k ()
io.fotoapparat.a.d.a.h ()
io.fotoapparat.h.c.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:818)
```

The device : BLU STUDIO C 5+5 
Android OS: 5.0

**Comment by Diolor** [comment]
Hi @jeffersonlicet  thanks for reporting this! Few questions:

1) How do you call FA's start/stop ?
2) Did you try reproduce to it? Would be very helpful if you provide us with the logs from our logger.

Thanks!

**Comment by jeffersonlicet** [comment]
Thanks four your time.
I start/stop FA using a FotoapparatSwitcher located in this static OpenCV code:
```
private BaseLoaderCallback mLoaderCallback = new BaseLoaderCallback(this) {
        @Override
        public void onManagerConnected(int status) {
            switch (status) {
case LoaderCallbackInterface.SUCCESS: fotoapparatSwitcher.start();
break;}
        }
    };
```

OpenCV starts here:
```
@Override
    public void onResume() {
        super.onResume();

        try {
            if (!OpenCVLoader.initDebug()) {
                OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_3_2_0, this, mLoaderCallback);
            } else mLoaderCallback.onManagerConnected(LoaderCallbackInterface.SUCCESS);
        } catch (Exception ex) {
            FirebaseCrash.report(ex);
        }
    }
```
I can't reproduce it, but i will try,  i think its related to the Blu phone.

**Comment by dmitry-zaitsev** [comment]
Is `mLoaderCallback` always called from the main thread?

**Comment by jeffersonlicet** [comment]
Yes, any clue?

**Comment by dmitry-zaitsev** [comment]
Hm, not yet. If `mLoaderCallback` would be called from background thread that would explain the issue. I suspect that you can reproduce this issue by quickly switching between cameras while OpenCV is being initialized.

Would it be possible for you to provide us with logcat? Make sure you pass `logger` parameter while creating `Fotoapparat`.

**Comment by dmitry-zaitsev** [comment]
I am closing this issue until there is more information available. As soon as we'll have logs I will reopen it.

**Comment by jeffersonlicet** [comment]
Thank you very much. Solved starting the camera in the main thread as you told me. <3
