### ISSUE TITLE
Camera mode forcing.

### ISSUE THREAD

**Issue by jd-alexander** [Fotoapparat/Fotoapparat#4]
Is there anyway I can use this library in a way where I am forcing it to only use the front facing camera?

**Comment by dmitry-zaitsev** [comment]
Sure!

When you create the instance of `Fotoapparat` just specify the `lensPosition` parameter:

```java
Fotoapparat
    .with(context)  
    .into(cameraView)
    .lensPosition(front())       // that
    .build();
```
