### ISSUE TITLE
Rotate Screen camera zoomed

### ISSUE THREAD

**Issue by brian1212** [Fotoapparat/Fotoapparat#42]
can you check it ,please.When i rotate screen portait to landscape, camera in landscape mode is zoomed,when i rotate back it normal.

**Comment by dmitry-zaitsev** [comment]
Could you please provide screenshots?

**Comment by brian1212** [comment]
My device set auto rotation.
when i open app in portrait and rotate to landscape.
![screenshot_20170616-094442](https://user-images.githubusercontent.com/25501446/27209980-736ac2be-5279-11e7-9a91-d45056f7b6d8.png)
![screenshot_20170616-094452](https://user-images.githubusercontent.com/25501446/27209993-894ce9cc-5279-11e7-9232-15c732d656e6.png)

when i open app in landscape mode and rotate to portrait
![screenshot_20170616-094517](https://user-images.githubusercontent.com/25501446/27210010-a295624c-5279-11e7-9086-696115af9ad2.png)
![screenshot_20170616-094534](https://user-images.githubusercontent.com/25501446/27210033-cd794dfc-5279-11e7-93f5-f6017801538a.png)

**Comment by dmitry-zaitsev** [comment]
Thanks for the screenshots - looks odd indeed. Could you please also provide us with the following information:

- Which device is that? Which OS version?
- Snippet of code where you initialize Fotoapparat
- XML layout in which you added CameraView

**Comment by brian1212** [comment]
i just run your demo.i test on nexus 4 rom NitrogenOS 7.1.2 and Samsung s5 rom 6.0.1.

**Comment by dmitry-zaitsev** [comment]
@brian1212 May I ask you to do a little debugging for us? Could you please check what values `RendererParameters` has in `TextureRendererView` line 101 when you start the app and when you rotate the screen?

**Comment by dmitry-zaitsev** [comment]
Alternatively, please try updating to 1.0.3. It will not fix the problem, but it will print more info to log, which would hopefully help us solve the issue.

**Comment by namnguyen211** [comment]
when i start camera
 Renderer parameters are: RendererParameters{previewSize=Size{width=1280, height=960}, frameRotation=270}
when i rotate right
Renderer parameters are: RendererParameters{previewSize=Size{width=1280, height=960}, frameRotation=180}
when i rotate left
Renderer parameters are: RendererParameters{previewSize=Size{width=1280, height=960}, frameRotation=0}

seem to be when i rotate screen camera start again.right?

**Comment by dmitry-zaitsev** [comment]
Hm, those seem to be correct values. Sorry to ask, but could you please also put a breakpoint at line 136 in `TexturerRendererView` and check which values `previewSize` take and which values are passed to this method call:

```java
getChildAt(0).layout(
                -extraX / 2,
                -extraY / 2,
                width - (extraX / 2),
                height - (extraY / 2)
);
```

**Comment by brian1212** [comment]
when i open app:
![screen shot 2017-07-10 at 9 08 14 am](https://user-images.githubusercontent.com/25501446/28000344-5f814dd4-654f-11e7-8ec9-c1c5aff67c19.png)
when i rotate right
![screen shot 2017-07-10 at 9 09 12 am](https://user-images.githubusercontent.com/25501446/28000360-8176a81c-654f-11e7-8660-5b68837fc403.png)
when i rotate left
![screen shot 2017-07-10 at 9 12 15 am](https://user-images.githubusercontent.com/25501446/28000427-e7f6cf40-654f-11e7-83e2-47274753ec39.png)

**Comment by Diolor** [comment]
Normally should not happen in v2. Feel free to comment
