### ISSUE TITLE
adding     implementation 'io.fotoapparat:fotoapparat:2.7.0' doenst work

### ISSUE THREAD

**Issue by 0xveya** [Fotoapparat/Fotoapparat#427]
i added this line     implementation 'io.fotoapparat:fotoapparat:2.7.0' and this gives me this error FAILURE: Build completed with 9 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mapDebugSourceSetPaths'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

9: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.fotoapparat:fotoapparat:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
       - https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 802ms
22 actionable tasks: 11 executed, 11 up-to-date

**Comment by dodko159** [comment]
Version 2.7.0 seems to be hosted on JCenter, so you need to add JCenter to your repositories.
...
repositories {
...
jcenter()
}

**Comment by sampene** [comment]
> Version 2.7.0 seems to be hosted on JCenter, so you need to add JCenter to your repositories. ... repositories { ... jcenter() }

jcentre() has shutdown

**Comment by harshpatel63** [comment]
[mvn repositories](https://mvnrepository.com/artifact/io.fotoapparat/fotoapparat/2.7.0) do show **SciJava Public** holding this library. Hence, add the SciJava's maven url to build.gradle (project level).

```
allprojects {
    repositories {
         ...
        maven {
            url "https://maven.scijava.org/content/repositories/public/"
        }
        ...
    }
}
```
