### ISSUE TITLE
Add the ability to implement your own SizeSelector

### ISSUE THREAD

**Issue by iAlex97** [Fotoapparat/Fotoapparat#44]
If you'd like to use other resolution than the provided `biggestSize()` and `smallestSize()` you can't or at least it's not documented. I'd like to do some JNI image processing and for that I need to find a sweet spot between the max and min resolutin.

**Comment by dmitry-zaitsev** [comment]
`biggsetSize()` and `smallestSize()` are actually returning an implementation of `SelectorFunction`. That is the interface which provides you with a list of available items (sizes in this case) and asks you to pick one of them.

`SelectorFunction` is public, so you can just provide your own implementation where you would normally call `biggestSize()`.

Here are some examples of implementation:
https://github.com/Fotoapparat/Fotoapparat/blob/master/fotoapparat/src/main/java/io/fotoapparat/parameter/selector/SizeSelectors.java
