### ISSUE TITLE
autofocus() callback

### ISSUE THREAD

**Issue by jeffersonlicet** [Fotoapparat/Fotoapparat#46]
Hi, thank you very much for your time. is there any way to get the autofocus callback? seems like FocusResult is not available from getCurrentFotoapparat().autoFocus();

Thank you again.

**Comment by dmitry-zaitsev** [comment]
Currently, the result of autofocus is not exposed, but we can improve that.

**Comment by jeffersonlicet** [comment]
it will be awesome. Thank you.

**Comment by dmitry-zaitsev** [comment]
Sorry for late reply, but could you please describe your use case a bit more? 

Currently, we are attempting to perform auto-focus for you when `takePicture` is called. So, I am evaluating the need for the actual result from `autoFocus`. On top of that, some devices are not always consistent with a result of the autofocus operation and might fail more often than you would normally expect them to, so handling autofocus result will get tricky pretty fast on a client side.

**Comment by jeffersonlicet** [comment]
Using OpenCV to process a frame, but first it need to ensure the camera is focused , then I process the frame with a specific algorithm. Thank you. It also can be used performing face recognition (to draw rectangles etc)

**Comment by dmitry-zaitsev** [comment]
OK, that makes sense. I will try to provide the solution until the end of this week.

If you are relying on frame processing you should also update to 1.0.4, which would noticeably improve the performance.

As for face detection - we just started working on a module for Fotoapparat which would do face detection without relying on Google Play Services: https://github.com/Fotoapparat/FaceDetector

**Comment by dmitry-zaitsev** [comment]
The feature is in master. You can expect it in the new release which will happen until the end of the week.

**Comment by jeffersonlicet** [comment]
Thank you very much.

**Comment by omarDG** [comment]
Hi,

Where to find the documentation related to the focus callback? I'm unable to find it.

Regards
