### ISSUE TITLE
question how to save photo as byte array

### ISSUE THREAD

**Issue by yp25** [Fotoapparat/Fotoapparat#49]
Hi, I want to know how to save photo captured as byte array directly. 
In this sample code : 
`private void takePicture() {
        PhotoResult photoResult = fotoapparatSwitcher.getCurrentFotoapparat().takePicture();

        photoResult.saveToFile(new File(
                getExternalFilesDir("photos"),
                "photo.jpg"
        ));

        photoResult
                .toBitmap(scaled(0.25f))
                .whenAvailable(new PendingResult.Callback<BitmapPhoto>() {
                    @Override
                    public void onResult(BitmapPhoto result) {
                        ImageView imageView = (ImageView) findViewById(R.id.result);

                        imageView.setImageBitmap(result.bitmap);
                        imageView.setRotation(-result.rotationDegrees);
                    }
                });
    }

`

I can read from photo.jpg and then save to byte array variable . But how to directly read the photo data as byte array? Thank you

**Comment by dmitry-zaitsev** [comment]
`PhotoResult` actually delivers photo as a byte array, and then `toBitmap` converts it to actual `Bitmap`. So, what you can do:

```java
photoResult
    .toPendingResult()
    .whenAvailable(photo -> {
        // photo.encodedImage - that's your byte array
        // pay attention to photo.rotationDegrees parameter
    });
```

**Comment by ElyDantas** [comment]
> `PhotoResult` actually delivers photo as a byte array, and then `toBitmap` converts it to actual `Bitmap`. So, what you can do:
> 
> ```java
> photoResult
>     .toPendingResult()
>     .whenAvailable(photo -> {
>         // photo.encodedImage - that's your byte array
>         // pay attention to photo.rotationDegrees parameter
>     });
> ```

Should be in the README :)
