### ISSUE TITLE
Permissions were not added to manifest

### ISSUE THREAD

**Issue by scifinder** [Fotoapparat/Fotoapparat#57]
Hello! I'm new to Android Studio. By the instruction I connected your library, but in the manifest file no permissions were added. Why?

**Comment by bachhuberdesign** [comment]
You have to manually add permissions to manifest. You will also need to handle the runtime permissions in your code. This is not a Fotoapparat issue; it is the same with every library on Android.

**Comment by dmitry-zaitsev** [comment]
Permissions will be added automatically when you try to build the app. You will not see them in your AndroidManifest, as they are added by the manifest merger.

If you are interested about the details, you can read about it here: https://developer.android.com/studio/build/manifest-merge.html
