### ISSUE TITLE
Add ability to zoom in zoom camera.

### ISSUE THREAD

**Issue by reyanshmishra** [Fotoapparat/Fotoapparat#61]
In Current versio I didn't find any zoom in zoom out functionality for camera.

**Comment by nbeuret** [comment]
+1 👍 
Handling pinch-to-zoom gesture would be a great feature !

**Comment by dmitry-zaitsev** [comment]
Thanks for the suggestion 👍  We'll try to include that into the next major release.

**Comment by dmitry-zaitsev** [comment]
Done 🎉  You can get it in the 1.3.0 (which would be available shortly).

**Comment by reyanshmishra** [comment]
cool
