### ISSUE TITLE
Change flash mode, focus mode without Fotoapparat recreation

### ISSUE THREAD

**Issue by bagrusss** [Fotoapparat/Fotoapparat#71]
If I want to change flash mode or focus mode on the opened camera, I always need to create new Fotoapparat instance.

**Comment by dmitry-zaitsev** [comment]
We know that this is an issue and we would also like to improve it. I am still thinking about how API should look like.

**Comment by dmitry-zaitsev** [comment]
Done! Now you can update configuration after Fotoapparat is started. You can expect this feature in 1.3.0 release (soon).
