### ISSUE TITLE
please verify your readme 

### ISSUE THREAD

**Issue by REBOOTERS** [Fotoapparat/Fotoapparat#76]
it should be 

`allprojects {
		repositories {
			...
			maven { url 'https://www.jitpack.io' }
		}
	}`

not 

`allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}`

**Comment by dmitry-zaitsev** [comment]
Maybe a stupid question, but why? Both work fine.

**Comment by dmitry-zaitsev** [comment]
Just verified on jitpack.io - current configuration is correct one.
