### ISSUE TITLE
Possibility of Custom Photo Size?

### ISSUE THREAD

**Issue by Not-ANinja** [Fotoapparat/Fotoapparat#78]
I've been briefly reading through the code, and was wondering if there was a way to use a custom photo size rather than the biggest or smallest possible?
Any help would be great.

**Comment by dmitry-zaitsev** [comment]
It is possible to some extent. The camera provides us with the list of supported photo sizes and we have to pick one of them. So, it is not possible to select any arbitrary size.

Functions such as `biggestSize()` are providing you an implementation of `SelectorFunction` which picks one size from the list of supported sizes. If you would like to pick size yourself all you have to do is to implement `SelectorFunction` yourself (which is quite straightforward, as it is just 1 method) and pick `Size` from the given list yourself.
