### ISSUE TITLE
Flash switch

### ISSUE THREAD

**Issue by MinchinWang** [Fotoapparat/Fotoapparat#81]
How to turn off the cell phone dynamically？

**Comment by dmitry-zaitsev** [comment]
If you are looking for a way to change flash dynamically - it is implemented but not published yet. We are working on that.

Here is how it will look like: https://github.com/Fotoapparat/Fotoapparat/tree/develop#update-parameters

**Comment by sonjameyer** [comment]
Do you maybe have an ETA on this?

**Comment by dmitry-zaitsev** [comment]
@sonjameyer you can expect it this Saturaday (26.08.2017).

**Comment by MinchinWang** [comment]
thank you very much~

**Comment by dmitry-zaitsev** [comment]
@sonjameyer @MinchinWang 1.3.0 is live now. Enjoy!
