### ISSUE TITLE
Exception java.lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by gabodroid** [Fotoapparat/Fotoapparat#91]
Got this error in Firebase on two devices: YuLong Coolpad 3600I, 6.0.1 and OPPO F1f, 5.1.1:

`Exception java.lang.RuntimeException: getParameters failed (empty parameters)
io.fotoapparat.routine.ConfigurePreviewStreamRoutine.run (ConfigurePreviewStreamRoutine.java)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)`

I'm using Fotoapparat 1.3.0. with the given configuration:
`fotoapparat = Fotoapparat.with(this)
                .into(cameraView)           
                .previewScaleType(ScaleType.CENTER_CROP) 
                .photoSize(biggestSize())
                .lensPosition(back())
                .focusMode(firstAvailable(
                        continuousFocus(),
                        autoFocus(),
                        fixed()          
                ))
                .frameProcessor(frameProcessor)
                .cameraErrorCallback(cameraErrorCallback)
                .build();`

I'm also logging events in Firebase, so I can see, that the camera was working properly, but when the user entered the Activity with the Camera 2nd (Oppo) or 4th (Coolpad) time, the crash happened.

**Comment by Diolor** [comment]
Should be fixed in v2. Feel free to reopen!
