### ISSUE TITLE
Exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by gabodroid** [Fotoapparat/Fotoapparat#92]
Got this error in Firebase on: Micromax Micromax Q334,5.1:

`Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setErrorCallback([REDACTED_DOMAIN_NAME]$ErrorCallback)' on a null object reference
io.fotoapparat.routine.StartCameraRoutine.run (StartCameraRoutine.java)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:818)`

I'm using Fotoapparat 1.3.0. with the given configuration:
`fotoapparat = Fotoapparat.with(this)
                .into(cameraView)           
                .previewScaleType(ScaleType.CENTER_CROP) 
                .photoSize(biggestSize())
                .lensPosition(back())
                .focusMode(firstAvailable(
                        continuousFocus(),
                        autoFocus(),
                        fixed()          
                ))
                .frameProcessor(frameProcessor)
                .cameraErrorCallback(cameraErrorCallback)
                .build();`

**Comment by Diolor** [comment]
If happens in v2 as well, feel free to comment
