### ISSUE TITLE
Camera1 preview is darker comparing to stock camera app

### ISSUE THREAD

**Issue by friendoye** [Fotoapparat/Fotoapparat#95]
I don't know how is it possible, but Fotoapparat preview seems darker comparing to stock camera app or another camera lib ([Camera-Kit](https://github.com/gogopop/CameraKit-Android)).

Seems like it's not depend on Android version or manufacture, but if you would like to get more info I'll add more detailed explanation of the problem.

**Comment by friendoye** [comment]
After my small investigation I've figured out, that using higher FPS for ```previewFpsRange()``` causes frames be more darker.

**Comment by Diolor** [comment]
Interesting to know. Should we close this issue as it's "expected behavior" from the camera API or the hardware?

**Comment by dmitry-zaitsev** [comment]
I believe it is an expected behavior. Also you might notice that other camera apps are cranking up the brightness of the screen when you open them.

**Comment by valterh4ck3r** [comment]
How to change brightness camera ?

**Comment by Diolor** [comment]
Try remove `.sensorSensitivity(highestSensorSensitivity())`

**Comment by friendoye** [comment]
From my experience, setting ```previewFpsRange(lowestFps())``` should make preview brighter.

**Comment by valterh4ck3r** [comment]
Really, it's true... Thanks @friendoye
